export { default as App } from './App/App';
export { default as ArtistInfo } from './ArtistInfo/ArtistInfo';
export { default as Button } from './Button/Button';
export { default as FollowLogin } from './FollowLogin/FollowLogin';
export { default as CommentInput } from './CommentInput/CommentInput';
export { default as Input } from './Input/Input';
export { default as CommentsList } from './CommentsList/CommentsList';
export { default as Comment } from './Comment/Comment';
export { default as Loader } from './Loader/Loader';